### ISSUE TITLE
Consider dropping the jQuery dependency

### ISSUE THREAD

**Issue by lnicola** [regosen/Gapless-5#16]
I believe that reasonably modern browsers (the ones that support HTML5 Audio) also support the standard APIs for the functionality that Gapless 5 needs from jQuery.

Would you consider accepting a pull request that replaces jQuery with native browser APIs?

**Comment by regosen** [comment]
If it works with all modern browsers, yes absolutely!  :D

**Comment by regosen** [comment]
Finally removed the jQuery dependency from Gapless 5, closing issue
