### ISSUE TITLE
Autoplay not working?

### ISSUE THREAD

**Issue by tinspin** [regosen/Gapless-5#20]
It worked a couple of weeks ago, did google plug it?

And to add to the pain even if you click the page the playback now has a gap.

Edit: "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page."

This "do no evil" plan has gone too far, natural selection is not a bad thing.

**Comment by tinspin** [comment]
Do you know why the playback has a gap now even when you re-allow autoplay?

**Comment by regosen** [comment]
I'm not sure what you mean by re-allowing autoplay.  Autoplay is dead, it seems.  I don't hear a gap in the demo page: https://ccrma.stanford.edu/~regosen/gapless5/

Can you give me an example and tell me which browser you're using?

**Comment by tinspin** [comment]
Ok, it was goldwave that added silence when converting from wav to mp3... sorry

**Comment by tinspin** [comment]
Ok, sorry to spam my potential misstakes here, but since 71.0.3578.98 (yesterday) gapless5 doesn't work at all? None of the GUI is responsive, I didn't change anything since yesterday... oh well thank god Google removed "Do no evil" from their guidance...

**Comment by switz** [comment]
Pretty sure autoplay can be bypassed by creating an audiocontext (source: https://stackoverflow.com/questions/50490304/audio-autoplay-not-working-in-chrome/52249399). I haven't fully tested it myself though.

I also built a new gapless library but it has some holes and doesn't seem to work quite perfectly across browsers if anyone is looking for a bit more modern library to contribute to. http://github.com/relistennet/gapless.js

**Comment by regosen** [comment]
I just tried the audiocontext suggestion from that link, by adding this to my script:
```
window.onload = function() {
  var context = new AudioContext();
}
```
But I still get the error if I attempt to autoplay.

**Comment by regosen** [comment]
Given browser policies and the failed attempt above, I've removed `playOnLoad` from the library and am closing this issue.
