### ISSUE TITLE
Needs typescript compatibility

### ISSUE THREAD

**Issue by acroyear** [regosen/Gapless-5#21]
It would be nice if this was typescript-ready.  Either by being rewritten in typescript or simply having a types.d file in the module.

**Comment by gonzaloarca** [comment]
Any advancements towards this? I'm heavily interested in seeing a types declaration file for this library.

**Comment by regosen** [comment]
I just took a stab at it with this pull request: https://github.com/regosen/Gapless-5/pull/47

Have a go at it and let me know if it works for you!

**Comment by gonzaloarca** [comment]
Wow, that was fast! Everything looks good so far. I'll use the package straight from the pull request and let you know if anything seems off.

Really appreciate it, cheers!

**Comment by gonzaloarca** [comment]
Heads up, I just got a type error when trying to set the `options` parameter for the `Gapless5` constructor call. The `LogLevel` members are all of type `number`, but the `options` parameter is defined as a string-string record `{ [x: string]: string; }`. So when trying to assign `logLevel` to `LogLevel.Debug` in the `options` argument, I get a `Type 'number' is not assignable to type 'string'` error.

**Comment by regosen** [comment]
Ah, thanks for catching that!  I just pushed a fix to the PR branch to loosen the types of constructor options

**Comment by regosen** [comment]
PR merged and npm package updated to 1.5.0
