### ISSUE TITLE
Gapless5 not compatible with media session API

### ISSUE THREAD

**Issue by BERNARDO31P** [regosen/Gapless-5#22]
Greetings,

I'm currently having trouble with connecting the gapless player with the [media session API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API). It has a strange behavior. 

- When playing a song after the page reloads: The notification disappears after five seconds.
- When playing the second song: The notification disappear after one minute?

What I also noticed is that as soon as the next part is played, the notification also disappears. (I coded a "buffering" system)
I've sent you my website to your Email, where you can test this behavior.

If you need any further information or access to the source code, I'll give it to you through Email.

Kind regards,
Bernardo

**Comment by BERNARDO31P** [comment]
I've found [this](https://developers.google.com/web/updates/2017/02/media-session) article about the media session API in which is written: 

> As the Web Audio API doesn't request Android Audio Focus for historical reasons, the only way to make it work with the Media Session API is to hook up an `<audio>` element as the input source to the Web Audio API. Hopefully, the proposed Web AudioFocus API will improve the situation in the near future.

As the Gapless5 library is using the Web Audio API, I hope this helps.

**Comment by BERNARDO31P** [comment]
The behavior has changed since the last Gapless version. 
The media notification is now not displayed at all.

I normally initialize the media notification before the song is playing, but I also tried initializing the media notification after the song is playing -> with the `onplay()` event, no difference.

**Comment by regosen** [comment]
The `<audio>` element is an HTML5 element, sounds like that workaround you posted is a hack to use both WebAudio and HTML5 audio simultaneously for the entire track.  Gapless5 stops the HTML5 stream as soon as the WebAudio one is fully buffered (to save browser memory).

Can you try adding `useWebAudio: false` to your Gapless5 init options?  That should keep the HTML5 audio stream around, but then you'll probably get gaps between tracks.  If this fixes the media session issue for you, I can add some kind of "keepalive" init option that will keep the HTML5 audio stream (albeit at the cost of memory).

**Comment by BERNARDO31P** [comment]
You are right, with these init options the media session API works, but gapless playback is no longer possible. Also, I had to add `singleMode: true`, otherwise the player will automatically play the other parts and thus stop playing with my system.

What I also noticed is that after each part this error is displayed in the console: `Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().` but only with `useWebAudio: false`

**Comment by regosen** [comment]
I just pushed a new build (1.2.0) with a new option called `keepAliveHTML5Audio`, you should be able to set that to `true` (instead of setting `useWebAudio` to `false`), that should work with the media session API but also keep things gapless.

The update also includes a fix for the play/pause error.

**Comment by BERNARDO31P** [comment]
I tried the new update. When I try to play something, you hear the audio tag for a short time as well as the audio from the web audio API. The notification appears but disappears when the audio tag is muted or removed.

**Comment by BERNARDO31P** [comment]
I also noticed that when you press the play button in the notification, it plays the audio tag and not the web audio API. 
Is it not possible to connect the audio source for the web audio API from the HTML5 audio tag? As mentioned in the second reply of mine: 

> the only way to make it work with the Media Session API is to hook up an <audio> element as the input source to the Web Audio API.

**Comment by regosen** [comment]
I'm sorry to hear that.  At this point I'm shooting in the dark because I don't use the media session API and I don't have an Android.

But I see that you just forked this repo, so if you're able to modify it to match your needs, I'd be happy to review a PR!

**Comment by BERNARDO31P** [comment]
I may have an idea.
You have added an option so that the audio tag is not deleted.
Could you add a new option that keeps the audio tag running, but at the lowest volume?

I tried to add it by myself but failed. Could you maybe try this? 
I guess that's the last possibility.

**Comment by regosen** [comment]
What if you maintained your own instance of the audio track for your purposes, by playing your own copy at the same time you receive the gapless.onplay callback?  The following player uses Gapless-5 in a similar way:  https://github.com/wertstahl/THE402

Which allows that player to visualize the music from HTML5 Audio data, while Gapless-5 does its own thing.   Here it is in action: https://the402.wertstahl.de/player

(By the way, I never received your email)

**Comment by BERNARDO31P** [comment]
You are a genius. The MediaSession API works. For this, I added an audio element that plays very quiet white noise.

However, I had to use an older version of the Gapless-5 library because the newer ones create a gap. Did you have to change anything in the main system because of me?


Btw, did you check the spam folder?
If so, I was blocked for some inexplicable reason. Here is my website, which I sent you in the mail: https://beta.bernardo.fm

**Comment by regosen** [comment]
I'm glad it helped!  Are you hearing gaps only when single tracks are looped, or are you also hearing gaps between different tracks?

**Comment by regosen** [comment]
(Also, would you like your music page to be featured in the Gapless-5 readme under Demos?)

**Comment by regosen** [comment]
I have a possible fix for the gap... can you try this version? https://github.com/regosen/Gapless-5/blob/refactor-position-setting/gapless5.js

**Comment by BERNARDO31P** [comment]
I've heard gaps between the single tracks themselves. 
The newer version fixed the gaps but now you can hear a little bit of the previous part after the next part started. (You can try it if you want so that you hear the problem)

I would be very happy if you'd add my page as an example of this library.

**Comment by BERNARDO31P** [comment]
It seems that the Gapless-5 library does not notice that the WebAudio API has already loaded and then always plays the audio tag first. After a few milliseconds, it then switches to the WebAudio API.

**Comment by regosen** [comment]
I don't understand how `singleMode: true` relates to defining the "next source".  The purpose of `singleMode: true` is for looping over the same track forever.

You can define the next source by using `addTrack` or defining the tracks up front in the constructor (examples can be found in the README).

**Comment by BERNARDO31P** [comment]
Well, that's pretty interesting because if I use `singleMode: false`, the Gapless player tries to play all tracks I've added to the queue. Note that it plays them in the order in which they are added.

I'm creating a music player in which you should be able to forward and backward inside the track, which results in the player having this queue:
```
{
   0: "Part from 0 to 10 seconds",
   1: "Part from 11 to 20 seconds",
   2: "Part from 101 to 120 seconds",
   3: "Part from 21 to 30 seconds"
}
```
When part 1 is playing then the next part is 3 and not 2. 
I then define it with `Gapless.gotoTrack(3);` which doesn't work when using `singleMode: false`, it only works when using `singleMode: true`

You know what I mean?

**Comment by regosen** [comment]
What happens if instead of using an index, you call `gotoTrack()` using the same path you had used in `addTrack()` or `{tracks: ...}`?  e.g.

```
gapless.addTrack('my_path/part_1.mp3');
gapless.addTrack('my_path/part_2.mp3');
gapless.addTrack('my_path/part_3.mp3');
...
gapless.gotoTrack('my_path/part_3.mp3');
```

**Comment by BERNARDO31P** [comment]
I tried it with gotoTrack and the source. The behavior is the same, you can still hear a weird glitching. 

I could reduce the gaps by changing from mp3 to wav.

**Comment by BERNARDO31P** [comment]
I tried it again with `singleMode: false` and there are no glitches nor any gaps. 

If you could add a function with which I can define which part is going to be next that would fix all problems. 

Example:
```
let gapless = new Gapless({});
gapless.addTrack("https://example.com/1.wav");
gapless.addTrack("https://example.com/4.wav");
gapless.addTrack("https://example.com/2.wav");
gapless.addTrack("https://example.com/3.wav");
gapless.addTrack("https://example.com/5.wav");

gapless.onplay = () => {
    gapless.nextTrack(3); // Because part 2 is ID 3 and not ID 2
}
```

As mentioned before, I need this because the Gapless player plays all parts sequentially when using `singleMode: false`.

**Comment by BERNARDO31P** [comment]
I could fix the glitching and made a pull request. Take a look and see if it's okay.
#26

**Comment by regosen** [comment]
I commented on the PR with a request for an adjustment.  If you make the requested change, I'll be happy to merge it!

As for your `gapless.nextTrack(3);` example, if you don't know the desired order of the tracks until you start playing, what if you just called addTrack, removeTrack or insertTrack as needed after play starts?  Like this:
```
let gapless = new Gapless({});
gapless.addTrack("https://example.com/1.wav");

gapless.onplay = () => {
   gapless.addTrack("https://example.com/2.wav");
   // etc.
}
```

**Comment by BERNARDO31P** [comment]
I know it's 0-indexed, I made that up to be more clear. 

I'm already doing that with `gapless.onplay` but a user should be able to skip to the desired position, for example from 10 seconds to 100 seconds which breaks the sequential sequence. This is why I need to define the next part.

**Comment by BERNARDO31P** [comment]
I've implemented the nextTrack() function which seems to work. I would be happy if you'd review the pull request.

**Comment by regosen** [comment]
Something else I just realized: if you queue a track that is further from the current load limit (for memory management purposes), it won't be pre-loaded for gapless playback.

So I used your PR as a reference and implemented my own version of it that also updates the loading queue.  The function is called `queueTrack` instead of `nextTrack`.  It's pushed to the master branch now.  Try it and see if it suits your needs!

**Comment by BERNARDO31P** [comment]
The new version does not work. I don't even understand the behavior now, it's pretty random. 
I guess the `onplayrequest` event isn't triggered on every `play()` call.
I'll be using my version.

**Comment by BERNARDO31P** [comment]
The newest version `1.3.3` does work but creates a gap between the parts.

**Comment by regosen** [comment]
I just inspected your `tools.js` file and it really reaches deep into Gapless's inner functions (including Gapless5FileList and Gapless5Source objects).  The best practice is to just use the interface exposed by Gapless5Player and described in the README, because with version updates there can be breaking changes to anything that goes deeper than that.

So I don't know how your direct manipulation of position, etc. can affect the gapless functionality, nor can I reliably support this.  Here's an example of what I mean (from your code):

```
gapless.playlist.sources[part["gid"]].setPosition(0);
```

That being said, I just pushed some more improvements (version 1.3.4), and if you use `logLevel: LogLevel.Debug` when initializing Gapless5Player that might help you troubleshoot things.

**Comment by BERNARDO31P** [comment]
Now there is an error when initializing the Gapless player:  `Uncaught ReferenceError: Cannot access 'LogLevel' before initialization`
And it's referencing this code line: `switch (options.logLevel || LogLevel.Info) { ... }`

**Comment by BERNARDO31P** [comment]
You're right, I could fix that problem it was the ServiceWorker. But the gapless library does still behave pretty strange:
Here is the behavior:
- Plays track nr. 1 and queues track nr. 2
- Plays track nr. 2 and queues track nr. 3
- Stops the playback but executes onplay() callback

It's very strange, I hope I could describe it as acceptable. 
I guess the queueTrack does not work every time? 

I've uploaded the newest version to beta.bernardo.fm and enabled LogLevel.Debug maybe you can find something.

**Comment by regosen** [comment]
Hmm, I just tried visiting your music page here: https://beta.bernardo.fm/#!page=music

But it says "We couldn't find any song with that search term" and doesn't have anything to play.

**Comment by BERNARDO31P** [comment]
Did you empty your cache?

**Comment by regosen** [comment]
Ah thanks, shift-refreshing the site helped.

I'm also able to queue a track several times in a row from the Gapless demo page, so I don't think it's related to queueTrack.  Here's the log output where it behaves as you said, going silent after the second segment.  I added some comments to describe what I think is going on:

```
// First segment (35/5) plays
Playing WebAudio: https://beta.bernardo.fm/system/song/35/5
music.js:378 play
gapless5.js:167 onEnded will be called in 4.97 sec

// next track (35/15) is queued before current track (35/5) stops
// NOTE: When you see "Loading track X" in the log, that happens immediately when `queueTrack()` is called.
gapless5.js:594 Loading track 3: https://beta.bernardo.fm/system/song/35/15
gapless5.js:167 onEnded will be called in 5.00 sec

// (35/5) ends and (35/15) starts
gapless5.js:426 Setting track number to 3
gapless5.js:140 Stopping: https://beta.bernardo.fm/system/song/35/5
gapless5.js:183 Playing WebAudio: https://beta.bernardo.fm/system/song/35/15
music.js:378 play
gapless5.js:167 onEnded will be called in 5.00 sec

// Something weird happens here, for some reason we're stopping+restarting (35/15)
music.js:391 next part
gapless5.js:167 onEnded will be called in 5.00 sec
gapless5.js:426 Setting track number to 3
gapless5.js:140 Stopping: https://beta.bernardo.fm/system/song/35/15
gapless5.js:183 Playing WebAudio: https://beta.bernardo.fm/system/song/35/15
music.js:378 play

// this is a bad sign, something is only going to play for 0.01 sec?
gapless5.js:167 onEnded will be called in 0.01 sec
gapless5.js:167 onEnded will be called in 5.00 sec

// and here is the biggest problem, looks like (35/15) ended BEFORE queueTrack was called for (35/20)
// That means: queueTrack() was called while play was already stopped.  queueTrack() won't unpause for you.  (Even if it did, it would be too late to prevent hearing a gap.)
gapless5.js:140 Stopping: https://beta.bernardo.fm/system/song/35/15
gapless5.js:594 Loading track 4: https://beta.bernardo.fm/system/song/35/20
35gapless5.js:140 Stopping: https://beta.bernardo.fm/system/song/35/15
2music.js:391 next part
```

So I would suggest investigating why it's not queueing the new track until after the previous track ends.

**Comment by BERNARDO31P** [comment]
Thank you for this extremely good explanation of what's happening. I could fix it by adding a `setTimeout()` without any timeout.
The problem was that the `onplay()` event of the next track is called before the `onended()` event of the previous track.
Which resulted in not updating the part index.

The problem is fixed for me. Thank you a lot.

**Comment by regosen** [comment]
Glad to hear it!  I'll have to think about the onended() vs onplay() ordering, but in the meantime I'll close this issue.
