### ISSUE TITLE
No promise when playing

### ISSUE THREAD

**Issue by BERNARDO31P** [regosen/Gapless-5#23]
The gapless library doesn't return any promise object. 
It's impossible to know when the sound is actually playing. 
It would be very useful if it could return any information.

**Comment by regosen** [comment]
While Gapless5 doesn't have promises (it was first developed before Promises existed), it has callbacks you can implement like this:

```
const player = new Gapless5(...);
player.onplay = () => console.log('play started');
```

More examples are in the README.  Does that help you?  In a future release we could have onplay() provide the current audio path being played.

**Comment by BERNARDO31P** [comment]
Thank you for the fast response. That helps a lot. 

Kind regards

**Comment by BERNARDO31P** [comment]
I need to reopen this issue because the `player.onplay = () => {}` callback is not the actual play event. It is triggered before the sound actually plays. I need a callback that actually fires when the sound actually plays.

**Comment by BERNARDO31P** [comment]
I tried to figure out what's happening and it seems like the `onplay()` callback is fired even before the audio has loaded.

**Comment by regosen** [comment]
Ok, I just pushed a new build (1.2.0) such that onplay reflects when play actually starts.  (I also added an onplayrequest which is when the user presses "play" or play is otherwise requested.  That's what the old onplay used to do, but not what people expected).  Try it now

**Comment by BERNARDO31P** [comment]
This update fixed the issue. Thank you a lot.
