### ISSUE TITLE
Audio hiccup when switching from HTML5 to WebAudio

### ISSUE THREAD

**Issue by TaToTanWeb** [regosen/Gapless-5#28]
**Describe the bug**
The song starts first with the HTML5 Audio, and restarts a second time (no seamless transition) when the WebAudio API has finished decoding the file.

**Steps to reproduce**
I've created an HTML file with the following code
```
<script src="gapless5.js" language="JavaScript" type="text/javascript"></script>
<script>
    var player = new Gapless5({logLevel: 1});
    window.addEventListener('click', () => {
        player.addTrack('audio/song.mp3');
        player.play();
    })
</script>
```

**Gapless5 version**
Version 1.3.6

**Demo**
You can check a demo of the problem I'm getting here: https://gapless5-test.surge.sh/

**Comment by regosen** [comment]
Thanks for reporting this!  I found the cause and submitted a new version (1.3.8) with the fix.  Can you try it again with the version 1.3.8?

**Comment by TaToTanWeb** [comment]
The problem disappeared with 1.3.8. Thank you so much!

**Comment by TaToTanWeb** [comment]
Sorry, I didn't notice before, but now I hear a small gap when the player whitches to WebAudio.
Here is a new demo (same code as before, with the new gapless5 version): https://gapless5-test2.surge.sh/

**Comment by regosen** [comment]
Oh, I see what you mean, seems like the two streams are not perfectly aligned.  This might take a while to investigate, but I think you could do one (or both) of the following as a workaround:

A) call `addTrack()` prior to the click.  That way the WebAudio stream will be fully loaded by the time you play it
B) initialize Gapless5 with `{useHTML5Audio: false}`

**Comment by regosen** [comment]
Update: I think I've fixed the audio hiccup as well with version 1.3.9, please try it out at your convenience.

**Comment by TaToTanWeb** [comment]
Thank you for your great work! I'm still hearing a difference between the two, but it's less noticeable now, so I don't think it would be a big problem for me to leave it there
In case you want to check it out, here is another demo with Gapless5 1.3.9: https://gapless5-test3.surge.sh/

**Comment by regosen** [comment]
The latest commit should have this resolved now: https://github.com/regosen/Gapless-5/commit/60c00f282de93e6cb6bfdd3b9f0d73a3ded34763
