### ISSUE TITLE
How to use scrub functionality with no-gui gapless-5? Or AudioContext.currentTime setter?

### ISSUE THREAD

**Issue by IsaacVraspir** [regosen/Gapless-5#29]
Hey, the gapless audio has been awesome! 

I'm mostly looking for a way to change the position of the song while it is paused. I want to use gapless-5 in a rhythm game so that whenever the user pauses to a menu and then resumes, it would rewind to start back on the beat. I have the rewinding amount, just need to know how to set the time on the song.

Thanks for any advice on this!

**Comment by regosen** [comment]
Good call, I just published a new version of the player (1.3.10) with a `setPosition()` function that takes in the position in milliseconds.  Please let me know if the new version works as desired for you!

**Comment by IsaacVraspir** [comment]
Thank you very much! I'll be trying it out on Monday and I'll let you know 👍

**Comment by IsaacVraspir** [comment]
Thank you @regosen, setPosition works great! 

Now I need a getCurrentPosition() that returns the position of the song in milliseconds please! The audioContext.currentTime is more of a hardware timer and isn't a representation of the current time of the file that is playing, especially after using setPosition. 
Let me know if that is possible, thanks again!

**Comment by regosen** [comment]
Done!  Try again with version 1.3.11.

Once your rhythm game is live, I'd be happy to link to it from the Demos section in our README!

**Comment by IsaacVraspir** [comment]
Thank you, things are going good! That's nice of you to feature us in the Demo section. Its a guitar learning website where you learn chords, rhythm and scales with our MIDI guitar! It might be a bit weird since it requires our MIDI guitar to actually play along with the game, but the preview would give a good demo anyways.

My next request for the player, if possible, is a different version of setPlaybackRate that doesn't change the pitch of the song. Since we're teaching them scales, the song needs to stay in the same key when we change playback rate. An example of it is here with the html audio player https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_av_prop_playbackrate 
If that's too big of a feature, we can always work around it and just make more versions of the song at different BPMs. 

Let me know, thanks for all your help!

**Comment by regosen** [comment]
Hi Isaac.  I could enable pitch preservation, but that feature is only supported for HTML5 Audio/Video (which is what your w3schools.com example uses). WebAudio doesn't have such functionality under the hood, so to use it Gapless5 would need to operate without WebAudio...which means you will hear gaps between tracks.

If that's fine for you, I could add an option called `preservePitchHTML5Only`, let me know!

**Comment by IsaacVraspir** [comment]
Ok that makes sense! I'll talk to the team tomorrow, but I'm thinking that we don't need the option if it brings gaps to the gapless player haha! Knowing that the looping is perfect with the gapless player, we can have shorter duration backing tracks and save more server storage space for copies with different BPMs. 

Thank you for looking into it for me!

**Comment by regosen** [comment]
No worries.  Once you confirm, would you mind closing this ticket?

**Comment by IsaacVraspir** [comment]
Yep, I confirmed we'll be ok if you don't add it. 

If you did want to, it looks like the way to do it on web audio is to reinitialize the player with a new sampleRate that is multiplied by the playbackRate percentage. Not sure if you detect the sample rate of the file as a default or if you would need that as a parameter to be passed in.
https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext#example

**Comment by regosen** [comment]
I just tried initializing with different sampleRate values, but it didn't affect the pitch or rate of the playback.  (Though I do hear it very low-passed when setting sampleRate to 8000, so I know the parameter is being used.)

**Comment by IsaacVraspir** [comment]
Oh sorry that's my bad! It must be changing the sample rate of the player for compatibility rather than the audio itself. Thanks for trying it out, we can close this issue now you've helped me a lot!
