### ISSUE TITLE
button actions are confusing

### ISSUE THREAD

**Issue by schrock** [regosen/Gapless-5#33]
This is more of a subjective issue than an actual bug. It appears the button functions mimic those of an old tape player, rather than those of virtually any digital audio player. In effect, this means that `pause()` and `stop()` do the exact same thing: pause playback without changing the position. When paused, `next()` and `previous()` do not automatically start playback. There also appears to be no way to repeat a single track after the player has been initialized.

I am not sure if the current behavior of these functions should be changed, as it might break existing clients of the library. It might be better to just add some more information to the README about the exact behavior.

For your reference, here are what the buttons in Foobar2000 do:
```
play -> starts playing the track from the beginning, even if it is already playing or paused
pause -> pauses the track is playing, resumes if paused
stop -> stops playback and resets the position to the beginning of the song
prev -> goes to the previous track in the playlist and starts playing from the beginning
next -> goes to the next track in the playlist and starts playing from the beginning
```

For your reference, this is how I mimiced the Foobar2000 behavior using Gapless-5:
```
const player = new Gapless5({ useWebAudio: false, loop: true, loadLimit: 2 });
var playerPaused = true;
var repeat = false;

// setup player callbacks
player.onplay = function () {
	playerPaused = false;
}
player.onpause = function () {
	playerPaused = true;
}
player.onstop = function () {
	playerPaused = true;
}
player.onnext = function (from_track, to_track) {
	if (repeat) {
		player.gotoTrack(from_track);
		player.cue();
	}
}

function audioStop() {
	player.stop();
	player.setPosition(0);
}

function audioPlay() {
	player.cue();
}

function audioPause() {
	if (playerPaused) {
		player.play();
	} else {
		player.pause();
	}
}

function audioSeekBackwards(seconds) {
	if (!playerPaused) {
		var position = player.getPosition();
		position -= 1000 * seconds;
		player.setPosition(position);
	}
}

function audioSeekForwards(seconds) {
	if (!playerPaused) {
		var position = player.getPosition();
		position += 1000 * seconds;
		player.setPosition(position);
	}
}

function audioPrevious() {
	player.prevtrack();
	player.cue();
}

function audioNext() {
	player.next();
	player.cue();
}

function audioRepeat() {
	if (repeat) {
		repeat = false;
	} else {
		repeat = true;
	}
}
```

**Comment by regosen** [comment]
You're right, changing the core behavior of these functions would break existing clients.  Though I wonder if some of your observations are due to bugs that are fixed now.  `stop()` should not be doing the same thing as `pause()`, it should be resetting to the start position.  Is that not the case for you?

I'm not sure how to respond to your point about "virtually any digital audio player", because these controls are based on how iTunes/Apple Music works (which I thought still had a significant share of the market).

**Comment by schrock** [comment]
`stop()` does not reset playback to the start position. I have to call `setPosition(0)` after calling `stop()` to get the desired behavior. I'll open another bug report for that.

It sounds like some of the stuff I'm seeing is due to bugs, so I will close this. Thank you.
