### ISSUE TITLE
Feature request to resolve click heard at loop point

### ISSUE THREAD

**Issue by viewescape** [regosen/Gapless-5#39]
Have been trying out using this to play short (~:60 second) white noise clips and I'm hearing a slight click at the loop point, more noticable with .mp3, however still noticable even using .wav original.  The only way I've resolved it was to switch over to doing a pure, no frills JS crossfade which negates all the other cool features of gapless-5, plus I can't do instancing.  Is it possible to add a crossfade feature to gapless-5?  Just on/off and var for # of seconds of crossfade

Here are some white noise clips to test with:  https://viewescape.com/audio/
(please note these are for testing only by author and are not for private/public use)

If you wear over-the-ear headphones, you'll hear the slight click at the loop point.  A crossfade resolves the issue, hence my suggested solution.  The white noise tracks in that link are perfectly seamless right down to the start/end sample and I was using FFmpeg concat to create long videos using them, however looking for a web based player solution for a new site - I could live with a second or 2 crossfade.  Gapless-5 is the closest solution yet ;D  Thanks!

**Comment by regosen** [comment]
Thanks for the report.  Gapless 1.4.0 has just been released with a possible fix for this.  Please let me know if you still encounter any issues.

(You can also customize the crossfade and lookahead for transitions between tracks, have a look at the [readme](https://github.com/regosen/Gapless-5/blob/main/README.md) and search for "crossfade")

**Comment by regosen** [comment]
(err, actually please use 1.4.1 instead!  It has a simpler crossfade interface and a couple of extra bugs fixed.)

**Comment by viewescape** [comment]
Great thank you!  Will try it out.
