### ISSUE TITLE
Partial content (206) causes issues

### ISSUE THREAD

**Issue by PerryRylance** [regosen/Gapless-5#41]
**Describe the bug**
Hi folks, just plugged this library in on an ES6 React environment being served up with `npm start`.

Data is being received and I've followed it all the way to line 433: `player.context.decodeAudioData(data)`.

This always fails.

I took a look at the docs for audio contexts and it looks like this is expected with partial content.

I'll need to adapt something to load the entire file before passing it to your library - my goal is to loop audio without missing a beat as it's a looping game soundtrack.

**Debug output**
Instructions for setting log level didn't work.

**Comment by regosen** [comment]
When you say the instructions for setting log level didn't work, do you mean that it didn't recognize the variable "LogLevel.Debug"?  If so, can you try initializing Gapless5 with `{ logLevel: 1 }` instead?

**Comment by regosen** [comment]
Also, that's surprising that it reaches `decodeAudioData` without loading the whole file first.  We only call that from the `onload` callback of FileReader (for blob data) or XMLHttpRequest (for files), and in either case the `onload` callback shouldn't be called until the loading is complete.

When you provide Gapless5 with a path to your audio file or blob, is the file/blob itself incomplete?

**Comment by PerryRylance** [comment]
Hmm, so, I came to try to reproduce this today so I could demonstrate only the first 2000 or so bytes are being served, it's now playing. Sorry! I guess something has changed at my end.

**Comment by regosen** [comment]
Hooray!  Closing this issue then.
