### ISSUE TITLE
currentLength() returns 0 during first seconds of playback

### ISSUE THREAD

**Issue by gonzaloarca** [regosen/Gapless-5#49]
**Describe the bug**
When using the `currentLength` method in the `Gapless5` object, the value returned is 0 during the first seconds of playback. I assume this has something to do with the duration not being available while the full audio is not yet available? 

**Debug output**
Here, I ran a test using the new `ontimeupdate` feature, where the current position is printed followed by the return value of the `currentLength()` call. The test implies calling the `play` method, while HTML5 audio is being used (i.e. hit play quickly before the full audio is downloaded).
```typescript
player.ontimeupdate = currentPosition =>
			console.log("ontimeupdate", currentPosition, player.currentLength());
```
```
ontimeupdate 3650 0
ontimeupdate 3987 0
Loadable indices: [0,1,2]
Switching from HTML5 to WebAudio: <url>
Loadable indices: [0,1,2]
ontimeupdate 3987 404950.20408163266
```

**Comment by regosen** [comment]
I just looked into this and pushed a fix in my PR where I utilize the loadedmetadata HTML5 event: https://github.com/regosen/Gapless-5/pull/47

Can you try latest from my branch to see if this is improved?

**Comment by gonzaloarca** [comment]
I'm afraid I'm getting the same behavior
