### ISSUE TITLE
On ios: player stops playing when navigating away from the browser and comes alive again when going back to the page.

### ISSUE THREAD

**Issue by coderdeluxe21** [regosen/Gapless-5#56]
Hi there,

On ios: player stops playing when navigating away from the browser and comes alive again when going back to the page.

There are other sites like soundcloud where the playing keeps playing in the background.

Is there a way to keep the audio alive when navigating away? Maybe a setting I have overlooked?

Thanks,
Moz

**Comment by regosen** [comment]
I'm googling this now, and it seems that the only fix is to have a second (HTML) audio element playing alongside it.  (e.g. https://stackoverflow.com/questions/69502340/ios-15-web-audio-playback-stops-working-in-safari-after-locking-screen-for-a-fe)

Thing is, I already have this workaround in Gapless5, though I pause it right away.  I just tried publishing a branch where I don't pause it, can you try it out?   https://github.com/regosen/Gapless-5/tree/rego/fix-background-pause

**Comment by mozzak** [comment]
Thanks awesome. I will look into it and report back.

On a different note. Did you come across the problem (yet) with iOS 17.4 and MediaElement? MediaElement stopped working for some reason. I am assuming this could have an impact on gapless5 as well.

**Comment by regosen** [comment]
My MediaElement are you talking about [MediaElement.js](https://www.mediaelementjs.com/)?  Gapless5 doesn't use that, though it does create HTMLAudioElements, which in turn inherit from HTMLMediaElement.

**Comment by mozzak** [comment]
I am referring to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement.

**Comment by regosen** [comment]
Ah, yes, we use that.  In my [Gapless 5 Demonstration Page](https://ccrma.stanford.edu/~regosen/gapless5/), the "Seamless audio" demo exclusively uses the HTMLMediaElement, and I can hear it on my iPhone with iOS 17.4.1.  So I haven't come across the problem.

**Comment by mozzak** [comment]
Great. Sorry for the off topic. I will test your background-pause-fix soon and let you know how it goes.

**Comment by coderdeluxe21** [comment]
I tested the version. navigating away from the browser to the home screen or other app still stops the audio.

**Comment by coderdeluxe21** [comment]
So this is what I have so far:

I generated two audio files (mp3s). Both are 10 seconds long. One with audio, one silent.
If you use the file with audio it works, if you use the silence file, it does not.
So it seems iOS reacts on the audio content.

**Comment by coderdeluxe21** [comment]
Actually what I said is not totally correct.
It seems it stops the gapless5 player but keeps playing the secondary audio, since the audio was silence I thought it stopped.
If you use a secondary audio file with content you will notice that both are playing. Once you move away from browser the secondary audio keeps playing while gapless5 audio stops. Strange stuff indeed.

**Comment by regosen** [comment]
Ah, this looks specific to WebAudio.  If I solely use HTML5Audio it works.  i.e.
```
    const audioPlayer = new Gapless5({
      useWebAudio: false,
      ...
```
But that means you'll get gaps between tracks.  (I suspect that's how soundcloud does it.)  If the gaps are not a deal-breaker for you, you could use that option.

**Comment by coderdeluxe21** [comment]
Unfortunately the main reason I have found gapless5 is because of the gapless playback :-)
This would be a dealbreaker for me.

Too bad iOS makes our life harder than it needs to be. Thanks for all the help though.
